spring:
  cloud:
    gateway:
      routes:
        - id: test_01
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: test_02
          uri: https://www.qq.com
          predicates:
            - Query=url,qq